### ISSUE TITLE
build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [versioncloud/vformat-aeson#1]
I tried building with aeson-2.0:

```
vformat-aeson                  > /tmp/stack-2ca428d73d0244ed/vformat-aeson-0.1.0.1/src/Text/Format/Aeson.hs:77:29: error:
vformat-aeson                  >     • Couldn't match type: Data.Aeson.KeyMap.KeyMap Value
vformat-aeson                  >                      with: M.HashMap T.Text a0
vformat-aeson                  >       Expected: M.HashMap T.Text a0
vformat-aeson                  >         Actual: Object
vformat-aeson                  >     • In the second argument of ‘M.lookup’, namely ‘obj’
vformat-aeson                  >       In the expression: M.lookup (T.pack k) obj
vformat-aeson                  >       In the expression:
vformat-aeson                  >         case (M.lookup (T.pack k) obj) of { (Just x) -> formatArg x }
vformat-aeson                  >    |
vformat-aeson                  > 77 |   case (M.lookup (T.pack k) obj) of (Just x) -> formatArg x
vformat-aeson                  >    |                             ^^^
```

**Comment by Akaame** [comment]
https://github.com/haskell/aeson/issues/881#issuecomment-944920664

says that [this](https://github.com/haskell/aeson/pull/866) changed the internal representation for `Data.HashMap.Strict` to  ` Data.Aeson.KeyMap`.

**Comment by Akaame** [comment]
@juhp here is a simple draft for updating this but I do not know batsh*t about stack as I am quite new to Haskell. Would appreciate if you could guide me on this one.

**Comment by juhp** [comment]
Looks okay to me though yes I would suggest to use CPP as you mention there.

See for example https://github.com/juhp/http-query/commit/5c7aff525137dcc8592f0011a96bbf146577faf9

Ah as for stack - I would honestly just omit your stack.yaml changes at the same time.

**Comment by gaoqiankun** [comment]
@juhp @Akaame 
I am very sorry for not replay in time. 

I haven't written code for over two years, and I rarely logged into this account during this period. I will merge your pull request #2 immediately. Since other people hardly use this library, I don't plan to maintain it anymore. If you think it is useful and want to maintain it, I can transfer it to you. 

Apologize again for any trouble I caused you.
